### ISSUE TITLE
[Beta 20151213] Streaming videos from server doesn't work

### ISSUE THREAD

**Issue by enoch85** [owncloud/android#1349]
When choosing to keep the photos and videos in the original place, the I can't play videos. I don't know if I'm supposed to be able to do that, but anyway, it doesn't work.

The video file also get downloaded randomly, or I mean, the question if I want to stream it with an external app, doesn't always pop up.

When I choose to move the files to the app folder, videos play without any issue.

**Phone**
OnePlus 2
Andoird 5.1.1

**Comment by tobiasKaminsky** [comment]
If you keep the files in original please then owncloud cannot play the videos/ show the images.
The streaming question should always appear if the file is not downloaded.
Can you provide me a step by step how to reproduce the problem?

**Comment by enoch85** [comment]
1. Take a video with the Beta app with the `kept in original folder` setting.
2. Open the video inside the Beta app.
3. Press play
4. Video doesn't play
5. Put the phone in landscape mode.
6. App crashes

**Comment by tobiasKaminsky** [comment]
Landscape crash should be fixed as it is the same as in #1348 right?
The other problem, I will have a look soon.

**Comment by enoch85** [comment]
> Landscape crash should be fixed as it is the same as in #1348 right? 

Yes, thanks!

**Comment by tobiasKaminsky** [comment]
Can you try it again?
There should be a fix in the latest beta?

**Comment by enoch85** [comment]
No, still can't stream (play).

Best Regards
Daniel Hansson
www.techandme.se

Sent from OnePlus Two, sorry for typos.

**Comment by tobiasKaminsky** [comment]
Same error? Or just no error?

**Comment by enoch85** [comment]
@tobiasKaminsky The landscape error is gone: https://github.com/owncloud/android/issues/1349#issuecomment-167346059 

But I can't play the videos from server, or stream if you want to call it that. Same error as before.

**Comment by elpraga** [comment]
I have the same issue, and it continues even with 20160305. None of the videos are being streamed (or reproduced) on my Nexus 5. 

I have had this issue for a long time, but I thought that it was due to my slow server, but during an upgrade to OC 9.0 yesterday I tried to play some videos in the web interface and it worked like a charm. Really very neat indeed.

I even tried to share a link to some video files and play them directly in BSPlayer (by adding "/download" to the link) and it worked without a glitch.

What information could I provide to help you debug the issue?

I am running the 20160305 on Nexus 5 with Android 6.0.1 and against OC 9.0 at the moment.

**Comment by elpraga** [comment]
..please note that I am able to play the same video files in beta 20160305 once they are downloaded using the internal player of the app.

**Comment by elpraga** [comment]
I'm also using HTTPS on my server. I'm trying to think about what information might be relevant.. 

Could you give me a hint what information would help you to investigate the bug @tobiasKaminsky or @AndyScherzinger ?

Unfortunately the tablet I used to have died, so I cannot double check the behavior on another device.

**Comment by tobiasKaminsky** [comment]
Can you give me a temporary account to your server and send me the credentials to owncloud@tobiaskaminsky.de?

**Comment by elpraga** [comment]
Ok, no problem. I'll do it today when I get home.

Thank you @tobiaskaminsky !

**Comment by elpraga** [comment]
I just did @tobiasKaminsky 

Thanks for the help!

**Comment by tobiasKaminsky** [comment]
I have tried it with latest beta:
opening the video within our app is not working (I remember that this never ever worked for me)
Then I tried "stream with external app":
bsplayerFree is not working
mxPlayer is working and one can jump between positions.

**Comment by elpraga** [comment]
Hello Tobias!
Thank you for trying it out.

> opening the video within our app is not > working (I remember that this
never     > ever worked for me)

Do you mean streaming the video within the app? That was what did not work
for me, but when I downloaded the video, I was able to play it within the
app. Did you try that? I also tried streaming the video from the web
interface, and it works nice even on the phone.

> Then I tried "stream with external app":
> bsplayerFree is not working

I never tried 'stream with external app' as the initial message scares me
too much and I don't want to even risk exposing my password, what I did was
'share the file with link' and then append "/download" at the end. This
played nicely in BSPlayer (full version).

What u don't understand is why the app cannot stream the video, but I'd
able to play it once downloaded? If it's possible to stream it on the phone
within the web interface, speed should not be a problem.

Do you have any idea what that could be and if it could be fixed?

**Comment by elpraga** [comment]
How could it be investigated @tobiasKaminsky ? 
It seems that if the app can play the file once downloaded, and if streaming works in the web interface even using the phone, it could be just a small glitch easy to fix, maybe?

Please note, that my hope comes from my ignorance and I'm aware of it. :-D

If you need additional information I could provide, please let me know..

**Comment by tobiasKaminsky** [comment]
The internal video player is a big mess :/ I do not know why it cannot stream.
So it would be the best to use an external app.
The warning is not meant this strong: VLC for instance shows the url of the file playing back: https://tobi:23vl@owncl....
So you/or someone  also looking on the display might see the password for a short time.
It is not exposed to the internet or somewhere else.

**Comment by elpraga** [comment]
Well, that is sad to hear.. 

I guess I'll stick with sharing the link and playing it. 

I don't like the idea of my password being visible in the history of the player.. .. And having to remember deleting it.

... Just my personal paranoia, I guess.. :)

**Comment by tobiasKaminsky** [comment]
as far as I have tried it, the url contains the password. But VLC replaces the url with the filename and does not show the url any longer. 
So, maybe give it a try? If the other apps show the password in cleartext then it is a mistake by these apps and they should replace the passwort with ***.

**Comment by elpraga** [comment]
@jancborchardt I guess you are the one to ask then, as I assume that you have been here for longer time then Tobias. Do you know why streaming in the in app player does not work even when it can play the file once downloaded? Do you know if it can be fixed?

**Comment by tobiasKaminsky** [comment]
@elpraga I was trying to get the streaming working with the internal player, but this just did not worked.
As far as I can recall it is a problem with the android media player that is used. Maybe this is getting better with android 5 or 6, but honestly I am fed up with the internal player ;)

So therefore I came up with the "stream with external app".

**Comment by davivel** [comment]
Beta process is going to change. Current beta branch will not be maintained anymore. Video streaming is not available yet in stable app, so this needs to be closed.

And thanks for reporting! :)
