### ISSUE TITLE
Beta 20150109: It is harder then before to distinguish selected files

### ISSUE THREAD

**Issue by elpraga** [owncloud/android#1415]
I am not sure when exactly that happened, but now I noticed that it is harder to see which files are selected in multiselect. 

Would You agree with me?

**Comment by tobiasKaminsky** [comment]
Do you mean the background color? The checkboxes are very good to distinguish, I think.

**Comment by elpraga** [comment]
I'm sorry,  I should have explained the case better.
They are indeed great for files and photos in list view and for files in
grid view.

I did have problems though with some photos in grid view. They were all
from the boat with blue background.

I gave it another thought and I think if the actual ✔ was changed from
transparent (now) to white,  it would make the distinction much more clear
for photos in blue.

**Comment by AndyScherzinger** [comment]
Ah, I get what you mean. @jancborchardt what do you think? This is imho true, so changing the check mark within the graphic to white would solve this issue but would also lead to stay with white background colors so the icon work still fits other screen. 

Any comment?

**Comment by cornzy** [comment]
I agree that the check mark needs to be white or light grey. I had the same problem that it is hard to see the checkbox in dark images in grid view. Another great approach for grid view is implemented in google fotos app. Aside the checkbox the thumbnail is displayed a bit smaller. Futher more the checkbox is displyed in the upper left corner, this position is much better for lefties (the left thumb hides the checkbox).

**Comment by jancborchardt** [comment]
Sounds good – let's do it like other established Material apps solve it.

**Comment by tobiasKaminsky** [comment]
@AndyScherzinger Can you do this?
But I have no clue in which PR, or if we need a new one?

**Comment by AndyScherzinger** [comment]
@tobiasKaminski sure thing. The original branch has already been merged, so I will have to create a new one targeting master. It'll only be a change of png files, so it will be easy to also push it to the beta branch :)

**Comment by AndyScherzinger** [comment]
@ all I fixed the images on a branch targeting master: #1424

**Comment by jancborchardt** [comment]
Btw @tobiasKaminsky @AndyScherzinger I just want to randomly thank you again for your great work and collaboration! :)

**Comment by AndyScherzinger** [comment]
Argh, my mistake... This fix is (only) needed for the multi select... @tobiasKaminsky do you want to pull this change to the branch and we then close this PR or should we keep it as a separate one like it is now?

@jancborchardt You are welcome and it is a pleasure. Besides that I also have to thank you and everyone else from the core team ans community for the collaborative way of pushing this app forward. To hand over the Thank You, I give it to @przybylski since he and @tobiasKaminsky did most of the community implementations for the next release! So Kudos to you guys!

**Comment by elpraga** [comment]
Did You managed to get the change to latest beta? I just checked in 20160124 and it still behaves as it used to, is that intentional?

**Comment by AndyScherzinger** [comment]
@elpraga yes it should be... can you post a screenshot so I can check? At least the changed icon work is on the beta branch.

**Comment by elpraga** [comment]
Hello @AndyScherzinger, I was just checking the issue and I noticed that there are indeed white checkmarks on Android 6.0, but transparent checkmarks remain on Android 4.1. Both versions checked with beta 20160124.

In other words, it is fixed on Android 6.0, and remains the same on 4.1.

Dis this help?

**Comment by AndyScherzinger** [comment]
Hi @elpraga yes that helped :) The problem was that I missed changing the the icon work on all densities so this will be fixed in the next beta :) :+1:

**Comment by AndyScherzinger** [comment]
@tobiasKaminski just wanted to let you know that I also fixed it on the beta branch.

**Comment by tobiasKaminsky** [comment]
new beta published.
Please test :)

**Comment by AndyScherzinger** [comment]
Nice! Thanks @tobiasKaminsky! @elpraga Does it work for you? (Works for me)

**Comment by elpraga** [comment]
sorry, still the same situation using 20160201. Works fine on Android 6.0, but still transparent on 4.1.

6.0 is a Nexus 5  y 4.1 a tablet. Do You need some more info?

**Comment by AndyScherzinger** [comment]
Strange, I check the icons again. Maybe I still missed one. Thanks for testing. I don't need more infos at the moment.

**Comment by AndyScherzinger** [comment]
Hi @elpraga I finally found the issue :) I committed a fix of the check boxes. @tobiasKaminsky just fyi I have also commited it to the beta branch https://github.com/owncloud/android/commit/52e7bd85dfe9c61655e9746e4767fb1d831671ed

**Comment by tobiasKaminsky** [comment]
@elpraga is this solved for you?

**Comment by elpraga** [comment]
Unfortunately my tablet with Android 4.1 died and as a result I have
nowhere to test it, because it was working on my phone previously.

I might have get hands on a tablet next week.

I'll post an update in a week.

**Comment by AndyScherzinger** [comment]
any update @elpraga? This should be fixed with the latest beta releases :)

**Comment by elpraga** [comment]
I'm really sorry, but my tablet died before I could check the fix. I have no way to check it now..

**Comment by AndyScherzinger** [comment]
OK, no worries! I would then close the issue and it can be reopened in case this comes up again (which it shouldn't) :)

**Comment by elpraga** [comment]
Great! Thank you @AndyScherzinger !
